application: elite-epoch-711
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css/COMPILED/
  static_dir: static/css/COMPILED

- url: /static/js/
  static_dir: static/js

- url: .*
  script: blog_site.wsgi.application

libraries:
- name: django
  version: 1.5
- name: MySQLdb
  version: "latest"
